package org.skvoz.android

internal fun errorText(code: String): String = when (code) {
    "profile_validation_failed" -> "Проверьте отмеченные поля."
    "input_too_long" -> "Ввод не принят: превышен предел поля. Измените значение и повторите."
    "always_on_mode_required" -> "Always-on управляет ВПН. Выберите ВПН для применения профиля или измените системные настройки Android."
    "permission_request_pending" -> "Дождитесь завершения текущего запроса разрешения Android."
    "invalid_port" -> "Укажите целый порт от 1 до 65535."
    "duplicate_ports" -> "HTTP и SOCKS5 должны использовать разные порты."
    "vpn_settings_unavailable" -> "Откройте настройки Android → Сеть → ВПН → SKVOZ."
    "app_selection_budget_exceeded" -> "Можно выбрать не более 512 приложений."
    "app_inventory_budget_exceeded" -> "Список превышает предел 4096 приложений. Выбор сохранён."
    "app_inventory_failed" -> "Не удалось загрузить список. Повторите обновление; выбор сохранён."
    "invalid_ca" -> "Файл не содержит действительные сертификаты центра сертификации."
    "ca_budget_exceeded" -> "CA: не более 256 КиБ и 64 сертификатов."
    "ca_import_failed", "trusted_ca_unavailable", "trusted_ca_export_failed" -> "Не удалось прочитать доверенный CA. Проверьте файл и повторите импорт."
    "runtime_lost", "timeout", "enrollment_failed", "enrollment_cancelled" -> "Соединение прервано. При доступной сети выполняется повторное подключение."
    "unsupported_family" -> "Сервер не поддерживает требуемое семейство адресов. Проверьте конфигурацию сервера."
    "battery_settings_unavailable" -> "На этом телефоне настройка недоступна. Откройте сведения о приложении SKVOZ и параметры батареи."
    "invalid_address" -> "Укажите DNS или IP и внешний порт; IPv6 — в квадратных скобках. Не более 260 символов."
    "invalid_login" -> "Логин: до 64 латинских букв, цифр, _ или -."
    "invalid_password" -> "Пароль должен содержать от 12 до 72 байт UTF-8."
    "profile_incomplete" -> "Заполните сервер, логин и пароль."
    "authentication_failed" -> "Сервер отклонил логин или пароль."
    "certificate_failed" -> "Проверка сертификата сервера не пройдена."
    "server_unavailable", "network_unavailable" -> "Сеть или сервер недоступны."
    "version_mismatch", "unsupported_version" -> "Версии клиента и сервера несовместимы."
    "empty_app_selection" -> "Для режима «Только выбранные» нужно выбрать приложение."
    "selected_app_missing" -> "Выбранное приложение удалено. Обновите список."
    "foreground_start_denied" -> "Android запретил запуск фонового соединения. Проверьте разрешения и настройки ВПН."
    "vpn_permission_required" -> "Нужно разрешение Android на ВПН."
    "notifications_denied" -> "Уведомления запрещены. Соединение видно в диспетчере активных приложений Android."
    "credential_key_missing", "credential_decrypt_failed", "credential_corrupt" -> "Сохранённый пароль не удалось расшифровать. Очистите данные приложения и настройте профиль заново."
    "settings_read_failed", "unsupported_settings", "invalid_settings" -> "Сохранённые настройки недоступны или несовместимы."
    "local_setup_failed" -> "Не удалось открыть локальные порты или интерфейс."
    else -> "Не удалось выполнить операцию ($code)."
}

internal fun metricLabel(key: String): String = when (key) {
    "packet_in" -> "IP-пакеты от приложений"
    "packet_out" -> "IP-пакеты к приложениям"
    "packet_dropped" -> "Отброшено IP-пакетов"
    "queue_bytes" -> "IP-очереди, байты"
    "queue_records" -> "IP-очереди, записи"
    "buffer_bytes" -> "Зарезервировано памяти, байты"
    "buffer_records" -> "Зарезервировано записей"
    "collection" -> "Номер сбора в текущем runtime"
    "samples" -> "Образцы"
    "elapsed_ms" -> "Время сбора, мс"
    "turns" -> "Циклы локального I/O"
    "native_us" -> "Локальный I/O, мкс"
    "drive_us" -> "Обработка сети и ожидания, мкс"
    "read_full" -> "Полные серии чтения TUN (16)"
    "write_full" -> "Полные серии записи TUN (16)"
    "read_block" -> "TUN: чтение WouldBlock"
    "write_block" -> "TUN: запись WouldBlock"
    "read_paused" -> "TUN: паузы при заполнении очереди"
    "core_turns" -> "Циклы готового Core"
    "core_turn_us" -> "Core: обработка и ожидания, мкс"
    "core_progress" -> "Core: работа до idle"
    "core_idle_count" -> "Core: входы в ожидание"
    "core_idle_us" -> "Core: ожидание и приём, мкс"
    "core_output_us" -> "Core: вывод, мкс"
    else -> key
}
