# frozen_string_literal: true
source 'https://rubygems.org'
ruby '4.0.7'
gem 'async', '= 2.46.0'
gem 'acme-client', '= 2.0.35'
gem 'bcrypt', '= 3.1.22'
gem 'faraday', '= 2.14.4'
gem 'faraday-retry', '= 2.4.0'
gem 'faraday-net_http_persistent', '= 2.3.1'
gem 'net-http-persistent', '= 4.0.8'
group :test do
  gem 'rspec', '= 3.13.2'
end
